export const SUPPORTED_CALENDAR_YEAR = 2026;
export const DEFAULT_BIRTH_DATETIME = `${SUPPORTED_CALENDAR_YEAR}-03-10T09:00`;
export const DEFAULT_TARGET_DATETIME = `${SUPPORTED_CALENDAR_YEAR}-07-01T00:00`;
